#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SPLASH_SCENE 0.5
#define TRANSITION_TIME 0.5
#define PIPE_SPAWN_FREQUENCY 0.003

#define PIPE_GAP 7
#define UPPER_SCREEN_PIPE_THRESHOLD 0.65
#define LOWER_SCREEN_PIPE_THRESHOLD 0.35

#define PIPE_MOVEMENT_SPEED 0.008

#define BIRD_COLLISION_BITMASK 0x000001
#define OBSTACLE_COLLISION_BITMASK 0x000002
#define POINT_COLLISION_BITMASK 0x000003

#define BIRD_FALLING_SPEED 0.003
#define BIRD_FLYING_SPEED 0.05
#define BIRD_FLY_DURATION 0

#define SCORE_FONT_SIZE 0.1

#endif // __DEFINITIONS_H__
